local L = LibStub("AceLocale-3.0"):NewLocale("SpectraUI", "deDE")
if not L then return end

L["%s is a layout for ElvUI."] = "%s ist ein Layout für ElvUI."
L["About"] = "Über"
L["AddOns 1"] = true
L["AddOns 2"] = true
L["Blizzard"] = true
L["Click the button below to finalize everything and automatically reload your interface. If you run into any questions or issues, feel free to join our |TInterface\\AddOns\\SpectraUI\\media\\discord_logo.tga:14:14|t  |CFF03FA6EDiscord|r for assistance!"] = "Klicke auf die Schaltfläche unten, um alles abzuschließen und Deine Benutzeroberfläche automatisch neu zu laden. Wenn Du Fragen oder Probleme hast, kannst Dich sehr gerne an unseren |TInterface\\AddOns\\SpectraUI\\media\\discord_logo.tga:14:14|t |CFF03FA6EDiscord|r wenden, um Hilfe zu erhalten!"
L["Credits"] = true
L["DISABLE"] = "Deaktivieren"
L["Details Embedded"] = "Details Einbettung"
L["ElvUI"] = true
L["Embedded to Chat"] = "In den Chat enbetten"
L["Essential Settings"] = "Wichtige Einstellungen"
L["Finished"] = "Fertig"
L["Frames"] = "Fenster"
L["Horizontal"] = true
L["Install"] = "Installation"
L["Installation Complete"] = "Installation abgeschlossen"
L["Left Chat"] = "Linker Chat"
L["On Retail, you can now copy and import the Blizzard interface profile."] = "In Retail kannst Du jetzt das Blizzard-Schnittstellenprofil kopieren und importieren."
L["Please press the continue button if you wish to go through the installation process, otherwise click the 'Skip Process' button."] = "Bitte klicke auf die Schaltfläche „Weiter“, wenn Du den Installationsvorgang durchführen möchtest, andernfalls klicke auf die Schaltfläche „Vorgang Überspringen“."
L["Portraits offset"] = "Portrait Versatz"
L["Right Chat"] = "Rechter Chat"
L["Run the installation process."] = "Führe den Installationsvorgang aus."
L["Settings"] = "Einstellungen"
L["Skip Process"] = "Vorgang Überspringen"
L["The %s installation process is designed to be straightforward. You'll be prompted through a series of steps to apply the interface to your system seamlessly. Once the installation is complete, you'll have access to the full suite of %s features"] = "Der Installationsprozess von %s ist unkompliziert. Du wirst durch eine Reihe von Schritten geführt, um die Schnittstelle nahtlos auf Dein System anzuwenden. Sobald die Installation abgeschlossen ist, hast Du Zugriff auf die kompletten %s-Funktionen"
L["The installation guide should pop up automatically after you have completed the ElvUI installation. If you wish to re-run the installation process for this layout then please click the button below."] = "Die Installationsanleitung sollte automatisch erscheinen, nachdem Du die ElvUI-Installation abgeschlossen hast. Wenn Du den Installationsvorgang für dieses Layout erneut ausführen möchtest, klicke bitte auf die Taste unten."
L["Theme Elements"] = "Themen Elemente"
L["These are the Weakauras that are available. Please click a button below to apply the new Weakauras."] = "Dies sind die verfügbaren Weakauren. Klicke unten auf eine Taste, um die neuen Weakauras anzuwenden."
L["These are the profiles that are available. Please click a button below to apply the profile for the AddOn."] = "Dies sind die verfügbaren Profile. Klicke unten auf eine Taste, um das Profil für das AddOn anzuwenden."
L["This process will install %s and allow you to choose between a Vertical or Horizontal layout. It will also activate the essential features of %s."] = "Dieser Vorgang installiert %s und ermöglicht Dir die Auswahl zwischen einem vertikalen und einem horizontalen Layout. Außerdem werden die wesentlichen Funktionen von %s aktiviert."
L["Vertical"] = "Vertikal"
L["Weakauras"] = true
L["Welcome to the installation for |CFFFFFFFFSpectra|r |CFF03FA6EUI|r"] = "Willkommen bei der Installation für |CFFFFFFFFSpectra|r |CFF03FA6EUI|r"
L["Welcome"] = "Willkommen"
L["|CFF00A3FFB|r|CFF00B4FFl|r|CFF00C6FFi|r|CFF00D8FFn|r|CFF00EAFFk|r|CFF00F6FFi|r|CFF00F6FFi|r - Programming"] = "|CFF00A3FFB|r|CFF00B4FFl|r|CFF00C6FFi|r|CFF00D8FFn|r|CFF00EAFFk|r|CFF00F6FFi|r|CFF00F6FFi|r - Programmierung"
L["|CFF03FA6EThe installation process is now complete!|r"] = "|CFF03FA6EDer Installationsvorgang ist jetzt abgeschlossen!|r"
L["|CFFC7D377Lillekatt|r  - Creator and provider of the Role Icons"] = "|CFFC7D377Lillekatt|r  - Schöpfer und Anbieter der Rollensymbole"
L["|CFFF63939Details not found!|r |CFFFFFFFF(details is not installed or enabled)|r"] = "|CFFF63939Details nicht gefunden!|r |CFFFFFFFF(Details ist nicht installiert oder aktiviert)|r"
L["|CFFF63939Important|r: Major updates to %s will require you to go through the installation process again, which may result in the loss of any changes you’ve made. Please make sure to back up your settings if needed!"] = "|CFFF63939Wichtig|r: Bei größeren Updates von %s musst Du den Installationsvorgang erneut durchführen, was zum Verlust aller vorgenommenen Änderungen führen kann. Bitte sichere Deine Einstellungen bei Bedarf!"
L["|CFFF63939Important|r: Skipping this step may lead to an incomplete and malfunctioning interface!"] = "|CFFF63939Wichtig|r: Das Überspringen dieses Schritts kann zu einem unvollständigen und fehlerhaftem Interface führen!"