local L = LibStub("AceLocale-3.0"):NewLocale("SpectraUI", "ptBR")
if not L then return end

L["%s is a layout for ElvUI."] = true
L["About"] = true
L["AddOns 1"] = true
L["AddOns 2"] = true
L["Blizzard"] = true
L["Click the button below to finalize everything and automatically reload your interface. If you run into any questions or issues, feel free to join our |TInterface\\AddOns\\SpectraUI\\media\\discord_logo.tga:14:14|t  |CFF03FA6EDiscord|r for assistance!"] = true
L["Credits"] = true
L["DISABLE"] = true
L["Details Embedded"] = true
L["Embedded to Chat"] = true
L["Essential Settings"] = true
L["Finished"] = true
L["Frames"] = true
L["Horizontal"] = true
L["Install"] = true
L["Installation Complete"] = true
L["Left Chat"] = true
L["On Retail, you can now copy and import the Blizzard interface profile."] = true
L["Please press the continue button if you wish to go through the installation process, otherwise click the 'Skip Process' button."] = true
L["Portraits offset"] = true
L["Right Chat"] = true
L["Run the installation process."] = true
L["Settings"] = true
L["Skip Process"] = true
L["The %s installation process is designed to be straightforward. You'll be prompted through a series of steps to apply the interface to your system seamlessly. Once the installation is complete, you'll have access to the full suite of %s features"] = true
L["The installation guide should pop up automatically after you have completed the ElvUI installation. If you wish to re-run the installation process for this layout then please click the button below."] = true
L["Theme Elements"] = true
L["These are the Weakauras that are available. Please click a button below to apply the new Weakauras."] = true
L["These are the profiles that are available. Please click a button below to apply the profile for the AddOn."] = true
L["This process will install %s and allow you to choose between a Vertical or Horizontal layout. It will also activate the essential features of %s."] = true
L["Vertical"] = true
L["Weakauras"] = true
L["Welcome to the installation for %s"] = true
L["Welcome"] = true
L["|CFF00A3FFB|r|CFF00B4FFl|r|CFF00C6FFi|r|CFF00D8FFn|r|CFF00EAFFk|r|CFF00F6FFi|r|CFF00F6FFi|r - Programming"] = true
L["|CFF03FA6EThe installation process is now complete!|r"] = true
L["|CFFC7D377Lillekatt|r  - Creator and provider of the Role Icons"] = true
L["|CFFF63939Details not found!|r |CFFFFFFFF(details is not installed or enabled)|r"] = true
L["|CFFF63939Important|r: Major updates to %s will require you to go through the installation process again, which may result in the loss of any changes you’ve made. Please make sure to back up your settings if needed!"] = true
L["|CFFF63939Important|r: Skipping this step may lead to an incomplete and malfunctioning interface!"] = true
L["Open %s Settings"] = true
L["Open Menu"] = true
L["Open Settings"] = true
L["ReloadUI (/rl)"] = true
L["toggle Details"] = true
L["|CFFF63939Error|r: Embedded System is disabled, you can enable it in the %s settings."] = true
L["|CFFFFFFFFLeft click:|r"] = true
L["|CFFFFFFFFRight click:|r"] = true
L["|cff0DB1D0Dlarge|r - Localization"] = true
-- new
L["Player Portrait Hide"] = true
L["Hides the player portrait if a target exists."] = true
